global:
  resolve_timeout: 5m

route:
  receiver: "libswap-alert"

receivers:
  - name: "libswap-alert"
    webhook_configs:
      - url: "http://host.docker.internal:8080/"
        send_resolved: true